name: Python Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install dependancies
        run: pip install -r requirements.txt
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Test
        run: |
          ls
          python ./src\\test.py
      - name: Coverage
        run: |
          coverage run .\src\test.py
          coverage json
          node ${GITHUB_WORKSPACE}/.github/coverage.js
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
